### ISSUE TITLE
The section on Configuring Spring Boot Actuator Endpoints for Apps Manager should include security best practices

### ISSUE THREAD

**Issue by asaikali** [pivotal-cf/docs-pivotalcf-console#8]
The section "Configuring Spring Boot Actuator Endpoints for Apps Manager" should explain exactly how the apps manager pulls the actuator end points securely from the boot app. It should also make recommendations on how security on the actuators should be handled as a best practice.

**Comment by bentarnoff** [comment]
Thanks, @asaikali. Hey @nebhale @pivotal-mikegresham would you be able to provide information on the above?

**Comment by nebhale** [comment]
Happy to.  The Spring Boot Apps Manager integration does not use the "standard" Spring Boot Actuators.  Instead it uses a specific set of actuators that are secured using the `spaceDeveloper` role for the space that the application runs in (effectively the same permissions that Apps Manager needs in order to view anything about the application).  Authentication and authorization are automatically delegated to the Cloud Controller and UAA without any configuration being required of the user.

In addition, as of Spring Boot 1.5.0, actuators are secured by default, even if Spring Security is not included meaning that they are secure and cannot be accessed without explicit configuration by the user.  This allows users to take advantage of the Spring Boot Apps Manager integration without accidentally exposing their actuators without security.

**Comment by bentarnoff** [comment]
Thanks @nebhale. I'll incorporate this into the "Configuring Spring Boot Actuator Endpoints for Apps Manager" topic.

**Comment by bentarnoff** [comment]
Hey @asaikali we've updated the topic with Ben's additional information. You can see the updated topic on our staging site (https://docs-pcf-staging.cfapps.io/pivotalcf/1-11/console/spring-boot-actuators.html), and it will be on our production site soon. I'm closing this issue for now, but please feel free to get in touch if you have any further feedback.
